services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    alexdwt_verifiedrequest.argument_resolver:
        class: AlexDwt\VerifiedRequestBundle\ArgumentResolver\Resolver
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

    alexdwt_verifiedrequest.exception_listener:
        class: AlexDwt\VerifiedRequestBundle\EventListener\ExceptionListener
        arguments:
            $incorrectInputParamsResponse: '@alexdwt_verifiedrequest.incorrect_input_params_response'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    alexdwt_verifiedrequest.incorrect_input_params_response:
        class: AlexDwt\VerifiedRequestBundle\Response\IncorrectInputParamsResponse